language: ruby
cache: bundler

rvm:
  - jruby
  - 2.1.2

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - lumir.olivares@koombea.com
    on_failure: change
    on_success: never